config/routes.rb
Rails.application.routes.draw do

   
 #Pay Routes
  get "pays", to: "pays#index"
  get "pays/:id", to: "pays#show"
  post '/pays', to: 'pays#create'
  get "pesapal/callback", to: "pays#pesapal_callback"
  
  # resources :pays
  # resources :destnations
  # resources :usrs
  # resources :books, only: [:index, :create, :update, :destroy, :show]
 
#Login Routes
  post '/login', to: "sessions#create"
  post '/signup', to: "usrs#create"
  delete '/logout', to: "sessions#destroy"

  # get "/loggedin", to: "usrs#loggedin"
  


  # Books Routes
  get '/books', to: 'books#index'
  post '/books', to: 'books#create'
  get '/books/:id', to: 'books#show'
  patch '/books/:id', to: 'books#update'
  delete '/books/:id', to: 'books#destroy'


  # Usrs Routes
  get '/usrs', to: 'usrs#index'
  post '/usrs', to: 'usrs#create'
  get '/usrs/:id', to: 'usrs#show'
  patch '/usrs/:id', to: 'usrs#update'
  delete '/usrs/:id', to: 'usrs#destroy'

  # Destnation Routes
  get '/', to: 'destnations#index'
  post '/destnations', to: 'destnations#create'
  get '/destnations/:id', to: 'destnations#show'
  patch '/destnations/:id', to: 'destnations#update'
  delete '/destnations/:id', to: 'destnations#destroy'


end

app/models/destnation.rb
class Destnation < ApplicationRecord
  has_many :books, dependent: :destroy
  has_many :usrs, through: :books

  validates :name, presence: true
  validates :location, presence: true
  validates :description, presence: true
  validates :price, presence: true
end

app/controllers/destnations_controller.rb
class DestnationsController < ApplicationController


  skip_before_action :authorized, only: [:index, :create, :show, :update, :destroy]

  rescue_from ActiveRecord::RecordInvalid, with: :render_unprocessable_entity_response


# GET /destnations or /destnations.json
   def index
   destnations = Destnation.select(:id, :name, :image, :location, :description, :price)
   render json: destnations
  end

  # GET /destnations/1 or /destnations/1.json
  def show
    destnation = Destnation.select(:id, :name, :image, :location, :description, :price).find(params[:id])
    render json: destnation
  end

  # POST /destnations or /destnations.json
  # POST /destinations or /destinations.json
  def create
    destnation = Destnation.new(destnation_params)

    if destnation.save
      render json: destnation, status: :created
    else
      render json: { errors: destnation.errors.full_messages }, status: :unprocessable_entity
    end
  end


  # PATCH/PUT /destnations/1 or /destnations/1.json
  def update
    destnation = Destnation.find(params[:id])
    destnation.update!(destnation_params)
    render json: destnation
  end
  

  # DELETE /destnations/1 or /destnations/1.json
  def destroy
    destnation = Destnation.find(params[:id])
    destnation.destroy
    head :no_content
  end

  private
    # Only allow a list of trusted parameters through.
  def destnation_params
    params.require(:destnation).permit(:name, :image, :location, :description, :price)
  end      
   

 def render_unprocessable_entity_response(exception)
      render json: { errors: exception.record.errors.full_messages }, status: :unprocessable_entity
    end
end

app/helpers/destnations_helper.rb
module DestnationsHelper
end

app/views/destnations/_form.html.erb
<%= form_with(model: destnation) do |form| %>
  <% if destnation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(destnation.errors.count, "error") %> prohibited this destnation from being saved:</h2>

      <ul>
        <% destnation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/destnations/edit.html.erb
<h1>Editing Destnation</h1>

<%= render 'form', destnation: @destnation %>

<%= link_to 'Show', @destnation %> |
<%= link_to 'Back', destnations_path %>

app/views/destnations/index.html.erb
<h1>destnations</h1>

<ul>
  <% @destnations.each do |destnation| %>
    <li><%= destnation.name %></li>
  <% end %>
</ul>

app/views/destnations/new.html.erb
<h1>New Destnation</h1>

<%= render 'form', destnation: @destnation %>

<%= link_to 'Back', destnations_path %>

app/views/destnations/show.html.erb
<%= link_to 'Edit', edit_destnation_path(@destnation) %> |
<%= link_to 'Back', destnations_path %>
<h1><%= @destnation.name %></h1>
<p><%= @destnation.description %></p>
<img src="<%= @destnation.image%>">
<p><%= @destnation.location %></p>
<p>Price: <%= @destnation.price %></p>