config/routes.rb
Rails.application.routes.draw do

   
 #Pay Routes
  get "pays", to: "pays#index"
  get "pays/:id", to: "pays#show"
  post '/pays', to: 'pays#create'
  get "pesapal/callback", to: "pays#pesapal_callback"
  
  # resources :pays
  # resources :destnations
  # resources :usrs
  # resources :books, only: [:index, :create, :update, :destroy, :show]
 
#Login Routes
  post '/login', to: "sessions#create"
  post '/signup', to: "usrs#create"
  delete '/logout', to: "sessions#destroy"

  # get "/loggedin", to: "usrs#loggedin"
  


  # Books Routes
  get '/books', to: 'books#index'
  post '/books', to: 'books#create'
  get '/books/:id', to: 'books#show'
  patch '/books/:id', to: 'books#update'
  delete '/books/:id', to: 'books#destroy'


  # Usrs Routes
  get '/usrs', to: 'usrs#index'
  post '/usrs', to: 'usrs#create'
  get '/usrs/:id', to: 'usrs#show'
  patch '/usrs/:id', to: 'usrs#update'
  delete '/usrs/:id', to: 'usrs#destroy'

  # Destnation Routes
  get '/', to: 'destnations#index'
  post '/destnations', to: 'destnations#create'
  get '/destnations/:id', to: 'destnations#show'
  patch '/destnations/:id', to: 'destnations#update'
  delete '/destnations/:id', to: 'destnations#destroy'


end

app/models/pay.rb
class Pay < ApplicationRecord
    belongs_to :book, optional: true
    belongs_to :usr, optional: true
  end
  

app/controllers/pays_controller.rb
require "uri"
require "json"
require "net/http"
class PaysController < ApplicationController
  skip_before_action :authorized, only: [:index, :create, :show, :update, :destroy]

  def index
    @pays = Pay.all
    render json: @pays
  end
  
  def show
    @pays = Pay.find(params[:id])
    render json: @pays.to_json
  end

 # Create a new pay object
  def create
  pay =Pay.create(pay_params)
    token = JSON.parse(get_pesapal_token)
    order = create_order(token['token'], pay)
    render json: order
  end
# This function sends a request to Pesapal API to obtain an authentication token
  def get_pesapal_token
    url = URI("https://cybqa.pesapal.com/pesapalv3/api/Auth/RequestToken")
    
    https = Net::HTTP.new(url.host, url.port)
    https.use_ssl = true
    
    request = Net::HTTP::Post.new(url)
    request["Content-Type"] = "application/json"
    request["Accept"] = "application/json"
    request.body = JSON.dump({
      "consumer_key": "qkio1BGGYAXTu2JOfm7XSXNruoZsrqEW",
      "consumer_secret": "osGQ364R49cXKeOYSpaOnT++rHs="
    })
    # Send the request and get a response
     # Return the body of the response as a string
    response = https.request(request)
   return response.read_body
  end

  def create_order(token, pay)
        # Fetching the user details for the pay.
    user = Usr.find(pay.usr_id)
    names = user.name.split(" ")

    url = URI("https://cybqa.pesapal.com/pesapalv3/api/Transactions/SubmitOrderRequest")

https = Net::HTTP.new(url.host, url.port)
https.use_ssl = true

request = Net::HTTP::Post.new(url)
request["Content-Type"] = "application/json"
request["Accept"] = "application/json"
request["Authorization"] = "Bearer "+token
request.body = JSON.dump({
  "id": SecureRandom.hex,
  "currency": "KES",
  "amount": pay.amount,
  "description": "Book for travel",
  "callback_url": "http://localhost:3000/pesapal/callback",
  "notification_id": "362b449d-2301-46fb-bc4f-ded9dcb31be6",
  "billing_address": {
    "email_address": user.email,
    "phone_number": nil,
    "country_code": "",
    "first_name": names[0],
    "middle_name": "",
    "last_name": names[1],
    "line_1": "",
    "line_2": "",
    "city": "",
    "state": "",
    "postal_code": nil,
    "zip_code": nil
  }
})

response = https.request(request)
return response.read_body

  end
# This method is used as a callback URL to receive the transaction status from Pesapal payment.
  def pesapal_callback
    #receive tracking id from url
    params = request.query_parameters
  # Retrieve the Pesapal API token from the server
    token = JSON.parse(get_pesapal_token)
 # Get the transaction status from the Pesapal API using the token and order tracking ID
    order = JSON.parse(get_transaction_status(token['token'], params['OrderTrackingId']))
# Redirect the user back to the home page with a message containing the transaction status description
    redirect_to '/?message='+ order['description']

  end

  # This method retrieves the transaction status from the Pesapal API using the provided token and order ID.
def get_transaction_status(token, order_id)
url = URI("https://cybqa.pesapal.com/pesapalv3/api/Transactions/GetTransactionStatus?orderTrackingId="+order_id)

https = Net::HTTP.new(url.host, url.port)
https.use_ssl = true

request = Net::HTTP::Get.new(url)
request["Authorization"] = "Bearer "+token

response = https.request(request)
return response.read_body

  end


  private

  def pay_params
    params.require(:pay).permit(:amount, :status, :method, :usr_id, :book_id)
  end
  
end

app/helpers/pays_helper.rb
module PaysHelper
end

app/views/pays/_form.html.erb
<%= form_with(model: pay) do |form| %>
<%= csrf_meta_tags %>
  <% if pay.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pay.errors.count, "error") %> prohibited this pay from being saved:</h2>

      <ul>
        <% pay.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pays/edit.html.erb
<h1>Editing Pay</h1>

<%= render 'form', pay: @pay %>

<%= link_to 'Show', @pay %> |
<%= link_to 'Back', pays_path %>

app/views/pays/index.html.erb
<h1>All Pays</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Status</th>
      <th>Amount</th>
      <th>Method</th>
      <th>Book ID</th>
      <th>User ID</th>
    </tr>
  </thead>
  <tbody>
    <% @pays.each do |pay| %>
      <tr>
        <td><%= pay.id %></td>
        <td><%= pay.status %></td>
        <td><%= pay.amount %></td>
        <td><%= pay.method %></td>
        <td><%= pay.book_id %></td>
        <td><%= pay.usr_id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pays/new.html.erb
<h1>New Pay</h1>

<%= render 'form', pay: @pay %>

<%= link_to 'Back', pays_path %>

app/views/pays/show.html.erb
<h1>Pay <%= @pay.id %></h1>

<p>Status: <%= @pay.status %></p>
<p>Amount: <%= @pay.amount %></p>
<p>Method: <%= @pay.method %></p>
<p>Book ID: <%= @pay.book_id %></p>
<p>User ID: <%= @pay.usr_id %></p>