config/routes.rb
Rails.application.routes.draw do

   
 #Pay Routes
  get "pays", to: "pays#index"
  get "pays/:id", to: "pays#show"
  post '/pays', to: 'pays#create'
  get "pesapal/callback", to: "pays#pesapal_callback"
  
  # resources :pays
  # resources :destnations
  # resources :usrs
  # resources :books, only: [:index, :create, :update, :destroy, :show]
 
#Login Routes
  post '/login', to: "sessions#create"
  post '/signup', to: "usrs#create"
  delete '/logout', to: "sessions#destroy"

  # get "/loggedin", to: "usrs#loggedin"
  


  # Books Routes
  get '/books', to: 'books#index'
  post '/books', to: 'books#create'
  get '/books/:id', to: 'books#show'
  patch '/books/:id', to: 'books#update'
  delete '/books/:id', to: 'books#destroy'


  # Usrs Routes
  get '/usrs', to: 'usrs#index'
  post '/usrs', to: 'usrs#create'
  get '/usrs/:id', to: 'usrs#show'
  patch '/usrs/:id', to: 'usrs#update'
  delete '/usrs/:id', to: 'usrs#destroy'

  # Destnation Routes
  get '/', to: 'destnations#index'
  post '/destnations', to: 'destnations#create'
  get '/destnations/:id', to: 'destnations#show'
  patch '/destnations/:id', to: 'destnations#update'
  delete '/destnations/:id', to: 'destnations#destroy'


end

app/models/usr.rb
class Usr < ApplicationRecord
has_many :books, dependent: :destroy
has_many :destnations, through: :books


    has_secure_password
    validates :password, presence: true

    validates :name, presence: true, uniqueness: true
end

app/controllers/usrs_controller.rb
class UsrsController < ApplicationController
  skip_before_action :authorized, only: [:index, :create, :show, :update, :destroy, :loggedin]

    # GET /users

    def index
      @users = Usr.all
      render json: @users
    end

    # GET /users/1

    def show
      @user = Usr.find(params[:id])
      if @user
      render json: @user
      else
        render json: {error: "User not found"}, status: :not_found
      end
    end

    # POST /users

     def create
      user = Usr.create(user_params)
      if user.valid?
        render json: { user: user }, status: :created
      else
        render json: { error: user.errors.full_messages.join(', ') }, status: :unprocessable_entity
      end
    end

    # PATCH/PUT /users/1
    def update
      if @user.update(user_params)
        render json: @user
      else
        render json: @user.errors, status: :unprocessable_entity
      end
    end

    # DELETE /users/1
    def destroy
      @user.destroy
    end

    # def loggedin
    #   user = Usr.find_by(id: params[:id]) 
    #   if(user)
    #      render json: {loggedin: true, user: user}
    #   else
    #      render json: {loggedin: false}
    #   end      
    # end


    private
      # Use callbacks to share common setup or constraints between actions.
      def set_user
        @user = Usr.find(params[:id])
      end
      # Only allow a list of trusted parameters through.
      def user_params
        params.permit(:name, :email, :password)
      end
end

app/helpers/api/v1/usrs_helper.rb
module Api::V1::UsrsHelper
end

app/helpers/usrs_helper.rb
module UsrsHelper
end

app/views/usrs/_form.html.erb
<%= form_with(model: usr) do |form| %>
  <% if usr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usr.errors.count, "error") %> prohibited this usr from being saved:</h2>

      <ul>
        <% usr.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/usrs/edit.html.erb
<h1>Editing Usr</h1>

<%= render 'form', usr: @usr %>

<%= link_to 'Show', @usr %> |
<%= link_to 'Back', usrs_path %>

app/views/usrs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usrs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usrs.each do |usr| %>
      <tr>
        <td><%= link_to 'Show', usr %></td>
        <td><%= link_to 'Edit', edit_usr_path(usr) %></td>
        <td><%= link_to 'Destroy', usr, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usr', new_usr_path %>

app/views/usrs/new.html.erb
<h1>New Usr</h1>

<%= render 'form', usr: @usr %>

<%= link_to 'Back', usrs_path %>

app/views/usrs/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_usr_path(@usr) %> |
<%= link_to 'Back', usrs_path %>